# Generated by Django 6.0.4 on 2026-06-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lewis44', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
